---
title: "Project 1: Linear regression"
format: revealjs
editor: visual
---

## Time table

| Week     | Date            | Planned Activity |        Delivery        |
|----------|:----------------|-----------------:|:----------------------:|
| ~~*39*~~ | ~~*Wed 23.09*~~ |  ~~*Project 1*~~ | ~~(Part 1 presented)~~ |
|          | ~~*Fri 25.09*~~ |  ~~*Project 1*~~ |  ~~*First Hand-in*~~   |
| *40*     | *Wed 30.09*     |      *Project 1* |   (Part 2 presented)   |
|          | *Fri 02.10*     |      *Project 1* |          *-*           |
| *41*     | *Wed 07.10*     |      *Project 1* |    *Final Hand-in*     |
|          | *Fri 09.10*     |              TBD |  Assignment, 5 points  |

## Project 1: Overall aim

Your overall aim is modelling of traffic load (number of vehicles per 1 hour) using two different data sources: traffic monitoring and weather.

. . .

You will use multiple linear regression and can apply all variations of this that you have learnt so far (transformations, categorical variables, interactions), or add new elements.

## Project 1: Grading

In general, we are looking for both **correctness** in use of methods, and your **understanding/reflections** regarding the data, you choices and your results.

**AI-use**: We expect you to take advantage of all available resources, but the challenge is to use them in a good way. (Your teachers and teaching assistants are also a resource...)

## Project 1: Part 1 (last week)

You have:

-   Gotten to know the data

-   Selected a response variable (y) for a regression model (some form of traffic load)

-   Selected/discussed potential covariates / predictors / explanatory variables (x) that you can use to model your chosen response

## Project 1: Part 2

**Modelling traffic load using linear regression**

. . .

For part 2 of the project you are working towards **a presentation of 10 slides**, including:

-   visualizations

-   data wrangling pipeline

-   model formulation and results

-   a tabloid newspaper article

-   a final timeline documenting your progress (piece together the reflection notes).

## Project 1: Part 2

**Modelling traffic load using linear regression**

The presentation should be coherent, this includes the visualizations.

. . .

The presentation will be evaluated against your Part 1 hand-in, so make sure to document and argue for major deviations from your initial plan.

. . .

*Not part of the final evaluation, but an extra 5 points earned on the first Friday following the project deadline: 5-10 minutes presentations (3 groups together).*
